In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("../social_media_dataset_united.csv")
df = pd.DataFrame(data)
df.head()

   age  screen_time_min social_media_platform
0   36              120              Facebook
1   44              190              Facebook
2   30              310              LinkedIn
3   23              460               YouTube
4   36              370                TikTok

In [3]:
df['screen_time_min'].head()

0    120
1    190
2    310
3    460
4    370
Name: screen_time_min, dtype: int64

In [4]:
df[df["age"] <= 18].head()

    age  screen_time_min social_media_platform
10   18              200             Instagram
12   17              420               YouTube
14   17              310              LinkedIn
27   17              360                TikTok
50   16              280               YouTube

In [5]:
df.describe()

               age  screen_time_min
count  7598.000000      7598.000000
mean     30.728086       209.368255
std      12.518441       110.738072
min      13.000000        10.000000
25%      21.000000       125.000000
50%      27.000000       194.000000
75%      38.000000       270.000000
max      69.000000       697.000000

średni czas przed ekranem to 209 min